# Generated by Django 3.2.8 on 2021-11-16 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FATInTimePeriod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('description', models.CharField(max_length=500)),
                ('days', models.IntegerField(default=30)),
                ('fats_needed', models.IntegerField(default=10)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
