# Generated by Django 4.2.13 on 2024-06-06 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afat', '0021_alter_afatlink_fleet'),
        ('corptools', '0059_invtypematerials_met_type'),
        ('afat', '0023_the_big_rename'),
    ]

    operations = [
        migrations.CreateModel(
            name='FATInTimePeriod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('description', models.CharField(max_length=500)),
                ('days', models.IntegerField(default=30)),
                ('fats_needed', models.IntegerField(default=10)),
                ('ship_names', models.ManyToManyField(blank=True, limit_choices_to={'group__category_id': 6}, to='corptools.eveitemtype')),
                ('fleet_type_filter', models.ManyToManyField(blank=True, to='afat.fleettype')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FATCogConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fleet_type_filter', models.ManyToManyField(blank=True, to='afat.fleettype')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
