# Generated by Django 4.0.8 on 2023-03-05 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afat', '0021_alter_afatlink_fleet'),
        ('fatfilters', '0003_alter_fatintimeperiod_ship_names'),
    ]

    operations = [
        migrations.AddField(
            model_name='fatintimeperiod',
            name='fleet_type_filter',
            field=models.ManyToManyField(blank=True, to='afat.afatlinktype'),
        ),
    ]
