# Generated by Django 4.2.8 on 2024-01-14 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afat', '0023_the_big_rename'),
        ('fatfilters', '0004_fatintimeperiod_fleet_type_filter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fatintimeperiod',
            name='fleet_type_filter',
            field=models.ManyToManyField(blank=True, to='afat.fleettype'),
        ),
    ]
