# Generated by Django 4.2.9 on 2024-03-15 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afat', '0023_the_big_rename'),
        ('fatfilters', '0005_alter_fatintimeperiod_fleet_type_filter'),
    ]

    operations = [
        migrations.CreateModel(
            name='FATCogConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fleet_type_filter', models.ManyToManyField(blank=True, to='afat.fleettype')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
