# Generated by Django 5.2.12 on 2026-05-30 12:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        # ("eve_sde", "0018_blueprintactivity_blueprintactivityproduct_and_more"),
        ("fatfilters", "0006_fatcogconfiguration"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fatintimeperiod",
            name="ship_names",
            field=models.ManyToManyField(
                blank=True,
                limit_choices_to={"group__category_id": 6},
                to="eve_sde.itemtype",
            ),
        ),
    ]
